#!/usr/bin/env php
<?php

define('PROJ_DIR', __DIR__);
require('vendor/autoload.php');

// init lazyrecord
$config = new LazyRecord\ConfigLoader;
$config->load('db/config/database.yml');
$config->init();

// run
$cli = new RDE\DNS\Bin\CLI;
$cli->runWithTry($argv);
